# Generated by Django 4.2.2 on 2023-06-19 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_news'),
    ]

    operations = [
        migrations.DeleteModel(
            name='News',
        ),
    ]
